config/routes.rb
Rails.application.routes.draw do

  root 'sessions#home'
  get '/signup' => 'cubers#new'
  post '/signup' => 'cubers#new'
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :cubers 
  resources :cube_times
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cube_time.rb
class CubeTime < ApplicationRecord

    belongs_to :cuber
    
end

app/models/cuber.rb
class Cuber < ApplicationRecord

    has_secure_password
    has_many :cube_times 

    validates :name, presence: true
    validates :name, presence: true, uniqueness: true
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in?
    helper_method :current_cuber
    helper_method :cube_types

    private 

    def logged_in?
        !!current_cuber
    end

    def current_cuber
        @current_cuber ||= Cuber.find_by(id: session[:cuber_id]) if session[:cuber_id]
    end

    def cube_types
        ["2x2", "3x3", "4x4", "5x5", "3x3-OH", "3x3-BF", "3x3-FM", "Megaminx", "Pyraminx", "Skewb", "Square-1", "6x6", "7x7"]
    end

    def authenticate 
        redirect_to login_path if !logged_in?
    end


end

app/controllers/cube_times_controller.rb
class CubeTimesController < ApplicationController

    before_action :authenticate

    def index 
        if logged_in?
            @cuber = current_cuber
            render :show
        else  
            redirect_to login_path
        end
    end

    def new 
            @cuber = current_cuber
        if logged_in?
            render :new
            #erb :"/cube_times/new"
        else  
            redirect_to login_path
        end
    end

    def create 
        if logged_in?
            #raise params.inspect
            if params[:cube_time] == "" || !params.include?(:cubetype)
                render :new
            #   redirect '/cube_times/new'
            else
                if is_number?(params[:cube_time])
                    @cube_time = CubeTime.create(cube_time: params[:cube_time], cube_type: params[:cubetype])
                    @cube_time.cuber_id = current_cuber.id
                    if @cube_time.save
                
                        redirect_to cube_times_path(@cube_time.id)
                    else  
                        render :new
                    end
                else
                  #redirect :"/sessions/error"
                end
            end
        else
            redirect_to login_path
        end
    end

    def cube_type 
        if logged_in? 
            @type = params[:cube_type]
            @cuber = current_cuber
            @times = CubeTime.where(cuber_id: @cuber.id).where(cube_type: params[:cube_type])
            if @times.empty? 
              redirect_to cube_times_path
            else
             @best_cube_time = @times.order(cube_time: :asc).first
             @average_cube_time = @times.sum("cube_time")/@times.count
             @last_5 = @times.last(5)
             erb :"/cube_times/type" 
            end
          else
            redirect_to login_path
          
          end  
    end

    def edit
        if logged_in?
            @cuber = current_cuber
            @cube_time = CubeTime.find_by_id(params[:id])
            if @cube_time && @cube_time.cuber_id == current_cuber.id
                render cube_times_path(@cube_time.id)
            else
                redirect_to cube_times_path
            end
        else
            redirect_to login_path
        end
        erb :"/cube_times/edit" 
    end

    def update
        if logged_in?
            @cuber = current_cuber
            @cube_time = CubeTime.find_by_id(params[:id]) 
            @cube_time.cube_time = params[:cube_time]
            @cube_time.save
          
            redirect "/cube_times/#{@cube_time.id}"
        else
            redirect_to login_path
        end
    end

    def destroy
        if logged_in?
            @cuber = current_cuber
            @cube_time = CubeTime.find_by_id(params[:id])
            @cube_time.destroy
      
            redirect "/cubers/show"
        else 
            redirect_to login_path   
        end
    end

    private

    def cube_times_params

    end
    
end

app/controllers/cubers_controller.rb
class CubersController < ApplicationController

    def index 
        @cubers = Cuber.all
    end
    #loads the signup form
    def new 
        @cuber = Cuber.new
    end

    #signup
    def create
        @cuber = Cuber.new(cubers_params)
        if @cuber.save 
        session[:cuber_id] = @cuber.id
        redirect_to cuber_path(@cuber)
        else
            render :new
        end
    end

    def show 
        if logged_in?
            @cuber = current_cuber
            @cube_times = CubeTime.where("cuber_id = ?", @cuber.id)
            @best_cube_time = @cube_times.order(cube_time: :asc).first
            @average_cube_time = @cube_times.sum("cube_time")/@cube_times.count
            @last_5 = @cube_times.last(5)
            
            render :show
            
          else
      
            render :new
          end 
    end

    private

    def cubers_params
        params.require(:cuber).permit(:name, :email, :password)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new 
        
    end

    def create 
        @cuber = Cuber.find_by(name: params[:name])
        if @cuber && @cuber.authenticate(params[:password])
          session[:cuber_id] = @cuber.id
            flash[:success] = "Welcome, #{@cuber.name}"
          redirect_to cuber_path(@cuber.id)
        else
            flash[:danger] = "Improper credentials given"
          redirect_to login_path
        end
    end

    def home 
    end

    #logout
    def destroy 
        session.clear
        redirect_to '/'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def navbar
        if logged_in?
            render "layouts/logged_in_navbar"
        else
            render "layouts/logget_out_navbar"
        end
    end  
end

app/helpers/cube_times_helper.rb
module CubeTimesHelper
end

app/helpers/cubers_helper.rb
module CubersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cube_times/edit.html.erb
<h3> <%= @cube_time.cube_time %></h3>

    <form action="/cube_times/ <%= @cube_time.id %>" method="POST">
        <input type="hidden" name="_method" value="PATCH">
        <input type="float" name="cube_time">
        <br>
        <input type="submit" value="Edit">
    </form>

app/views/cube_times/new.html.erb
<br><h2><%= @cuber.name %>, Select Cube Type & Enter Your Cube Times Here</h2>
    <h3>Select Cube Type:</h3>


    <form action="/cube_times" method="POST">
        <% cube_types.each do |type| %>
        <input type="radio" name="cubetype" id="<%= type %>" value="<%= type %>"><%= type %></input></br>
        <% end %>

    <h3>Enter Your last Cube Time here:</h3>


        <label for="cube_time">Time:</label>
        <input id="cube_time" type="float" name="cube_time">
        <input type="submit" value="Enter">
    </form>

app/views/cube_times/show.html.erb
<h2><%= @cuber.name %>'s Last Cube Time</h2>
    <p><%= @cube_time.cube_time %></p>
    <br>
    <a href="/cubers/index"><input type="submit" value="Cuber HomePage"></a>
    <br>
    <a href="/cube_times/<%= @cube_time.id %>/edit">
    <input type="submit" value="Edit Time"></a>
    <form method="POST" action="/cube_times/ <%= @cube_time.id %>/delete">
        <input type="hidden" type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Delete">
    </form>

app/views/cube_times/type.html.erb
<% cube_types.each do |type| %>
    <a href='/cube_times/type/<%= type %>'><button type="submit"><%= type %></button></a>
    <% end %>

<h1>Your <%= @type %> Stats</h1>

            <% if @best_cube_time %>
                <p>Personal Best: <br> <%= @best_cube_time.cube_time %></p>
                <p>Overall Average: <br> <%= @average_cube_time.round(2) %></p>
            
                <p>Last 5 Cube Times: </p>
                <% @last_5.each do |x| %>
                <p><%= x.cube_time %> - <%= x.created_at.strftime("%b, %d, %Y") %></p>
                <% end %>
            <% else %>
                <%= "You have no cube times currently, let's change that!!" %>
            <% end %>

app/views/cubers/new.html.erb
<h3>Welcome, you're about to take your first step to SpeedCubing Domination !!</h3>
    <br>

    <%= form_for(@cuber) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Sign up" %>

    <% end %>

    <% if @cuber.errors.any? %>
        <% @user.errors.full_messages.each do |msg| %>
        <p style="color: red"><%= msg %></p>
        <% end %>
    <% end %>

app/views/cubers/show.html.erb
    <br><h2><%= @cuber.name %>'s Home Page</h2>

    <% cube_types.each do |type| %>
    <a href='/cube_times/type/<%= type %>'><button type="submit"><%= type %></button></a>
    <% end %>
    <br>

        <% if @last_5 %>
            <br><p><%= "Last 5 Cube Times:" %></p>
            <% @last_5.each do |x| %>
            <p><%= x.cube_time %> - <%= x.cube_type %> - <%= x.created_at.strftime("%b, %d, %Y") %></p>
        
            <% end %>
        <% else %>
            <br><%= "You have no Cube Times currently, let's change that!!" %>
        <% end %>   


    

app/views/layouts/_logged_in_navbar.html.erb
<%= button_to "Logout", logout_path, method: :delete %>

app/views/layouts/_logget_out_navbar.html.erb
<%= button_to "Log in", login_path %>

or

<%= button_to "Sign up", signup_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubiksTimeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <% flash.each do |k, v| %>
  <div class=<%= k %>><%= v %></div>
  <% end %>
  <%= navbar %>
  </header>
    
    <%= yield %>
  
  </body>
</html>